### ISSUE TITLE
change schema for `authority` of `alternate-identifiers` from `entity-id` to `generic-identifier`

### ISSUE THREAD

**Issue by catkins-miso** [trolie/spec#218]
The current schema for `power-system-resources.alternative-identifiers.authority` is `entity-id`:
```yaml
entity-id:
  description: Usually the NERC id of the entity.
  type: string
  maxLength: 10
  pattern: ^[A-Z\-]{3,10}$
  example: MISO
```

Since a given entity may have multiple naming authorities, i.e., systems which have unique primary identifiers for the same power system resource, `entity-id` is inappropriate. Instead, the schema should be `generic-identifier`:
```yaml
generic-identifier:
  type: string
  description: |

    Contains a unique identifier for an object. 
  maxLength: 250
  pattern: ^(.){0,250}$
  example: //trolie.example.com/limits/forecast-snapshot/2025-07-05T01:00:00-0500
```
